# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.namespace }}-container
          image: {{ .Values.container.image }}
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "500Mi"
              cpu: "0.5"
            limits:
              memory: "500Mi"
              cpu: "1"
